version: '3.9'
services:

  mongo:
    image: mongo
    restart: always
    ports:
      - '${MONGODB_PORT}:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '${MONGO_EXPRESS_PORT}:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASSWORD}

  openfire-xmpp:
    image: nasqueron/openfire:4.7.5
    volumes:
      - openfire-xmpp:/var/lib/openfire
      - ${HOST_LOG_DIRECTORY_PATH}/logs/openfire-xmpp/:/var/logs/openfire
    ports:
      - '${XMPP_ADMIN_PORT}:9090'
      - '${XMPP_USER_PORT}:5222'
      - '7777:7777'

  spade:
    build:
      dockerfile: docker/spade/Dockerfile.dev
    ports:
      - '${SPADE_PORT}:8080'
    environment:
      LOG_DIRECTORY_PATH: ${LOG_DIRECTORY_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
    volumes:
      - ${HOST_LOG_DIRECTORY_PATH}/logs/spade/:${LOG_DIRECTORY_PATH}
      - ./core/src:/app

volumes:
  openfire-xmpp:
