version: '3.9'
services:

  openfire-xmpp:
    image: nasqueron/openfire:4.7.5
    volumes:
      - openfire-xmpp:/var/lib/openfire
      - ${HOST_LOG_DIRECTORY_PATH}/logs/openfire-xmpp/:/var/logs/openfire
    ports:
      - '${XMPP_ADMIN_PORT}:9090'
      - '${XMPP_USER_PORT}:5222'
      - '7777:7777'

  spade:
    build:
      context: ./
      dockerfile: ./docker/spade.Dockerfile
    ports:
      - '${SPADE_PORT}:8080'
    environment:
      LOG_DIRECTORY_PATH: ${LOG_DIRECTORY_PATH}
      LOG_LEVEL: ${LOG_LEVEL}
      XMPP_SERVER_URL: ${XMPP_SERVER_URL}
      MODULE_DIRECTORY_PATH: ${MODULE_DIRECTORY_PATH}
    volumes:
      - ${HOST_LOG_DIRECTORY_PATH}/logs/spade/:/app/${LOG_DIRECTORY_PATH}
      - ./core/src:/app
      - ./modules:/app/${MODULE_DIRECTORY_PATH}

volumes:
  openfire-xmpp:
