FROM python:3.9.7
WORKDIR /app

COPY ../../core/requirements.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

ADD ../../core/src /app
CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
