# data preprocessing
numeric_features = ['calories',
 'carbohydrates',
 'current_daily_calories',
 'fat',
 'fiber',
 'height',
 'price',
 'projected_daily_calories',
 'protein',
 'weight',
'day_number',
'time_of_meal_consumption']
categorical_features = [
  'BMI',
  'age_range',
  'allergens',
  'allergy',
  'clinical_gender',
  'cultural_factor',
  'cultural_restriction',
  'current_working_status',
  'ethnicity',
  'life_style',
  'marital_status',
  'next_BMI',
  'nutrition_goal',
  'meal_type_y',
  'taste',
  'place_of_meal_consumption',
  'social_situation_of_meal_consumption'
 ]
embedding_features = ['cluster']
# entity features
user_features_list = ['nutrition_goal', 'clinical_gender', 'age_range',
                      'life_style', 'weight', 'height',
                      'projected_daily_calories', 'current_daily_calories',
                      'cultural_factor', 'allergy',
                      'current_working_status', 'marital_status', 'ethnicity',
                      'BMI', 'next_BMI']
#food_features = ['recipe_name', 'recipe_raw_text', 'meal_type_y',
#      'food_cultural_class', 'calories', 'allergens', 'recipeId']
food_features = ['cultural_restriction', 'calories', 'allergens', 'taste', 'price',  'fiber', 'fat', 'protein', 'carbohydrates'] #'recipeId',
context_features  = ['day_number', 'meal_type_y','time_of_meal_consumption', 'place_of_meal_consumption', 'social_situation_of_meal_consumption']
label_list = ['label']

sample = {'BMI': ['healthy'], 
     'age_range': ['30-39'], 
     'allergens': ["tree nuts"], 
     'allergy': ["soy"], 
     'calories': [650], 
     'carbohydrates': [39], 
     'clinical_gender': ['M'], 
     'cultural_factor': ['vegan_observant'], 
     'cultural_restriction': ['vegetarian'], 
     'current_daily_calories': [1700], 
     'current_working_status': ['Unemployed'],  
     'day_number': [0], 
     'recipeId': 'food_0', 
     'ethnicity': ['White'], 
     'fat': [30], 
     'fiber': [29], 
     'height': [165], 
     'life_style': ['Sedentary'], 
     'marital_status': ['Single'], 
     'meal_type_y': ['lunch'], 
     'next_BMI': ['healthy'],  
     'nutrition_goal': ['maintain_fit'], 
     'place_of_meal_consumption': ['home'], 
     'price': [2], 
     'projected_daily_calories': [2200], 
     'protein': [30], 
     'social_situation_of_meal_consumption': ['alone'], 
     'taste': ['sweet'], 
     'time_of_meal_consumption': [12.01], 
     'weight': [65]}