from enum import Enum


class Environment(Enum):
    LOG_DIRECTORY_PATH = 'LOG_DIRECTORY_PATH'
    LOG_LEVEL = 'LOG_LEVEL'
    XMPP_SERVER_URL = 'XMPP_SERVER_URL'
    MODULE_DIRECTORY_PATH = 'MODULE_DIRECTORY_PATH'
