name: hemerapp
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_chat_ui: ^1.6.9
  flutter_svg: ^2.0.6
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  flutter_tts: ^3.8.3
  json_annotation: ^4.8.1
  http: ^1.0.0
  provider: ^6.0.5
  speech_to_text: ^6.4.1
  web_socket_channel: ^2.4.0
  webview_flutter: ^4.2.2
  uuid: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - .env
